{{- $outer := . -}}
{{ range .Values.apps }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-svc
  labels:
    managed-by: Helm
    release: {{ $.Release.Name }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .service.port }}
      protocol: TCP
      name: http
  selector:
    name: {{ .name }}
{{ end }}