spring:
  application:
    name: demo

logging:
  level:
    org.zalando.logbook: TRACE

petstore:
  url: http://localhost:20001

management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"