version: '3'

services:
  error-handling:
    image: com.kainos/error-handling:$DOCKER_TAG
    ports:
      - "10001:8080"
    environment:
      JVM_OPTS: $JVM_OPTS
      KAFKA_BROKER: $URL_KAFKA_BROKER
      KAFKA_SCHEMA_REGISTRY: $URL_KAFKA_SCHEMA_REGISTRY
      ETCD_ENDPOINT: $URL_ETCD

  demo:
    image: com.kainos/demo:$DOCKER_TAG
    ports:
      - "10002:8080"
    environment:
      JVM_OPTS: $JVM_OPTS
      PETSTORE_URL: $URL_EXTERNAL_PETSTORE
      KAFKA_BROKER: $URL_KAFKA_BROKER
      KAFKA_SCHEMA_REGISTRY: $URL_KAFKA_SCHEMA_REGISTRY
      ETCD_ENDPOINT: $URL_ETCD

  api-gateway:
    image: com.kainos/api-gateway:$DOCKER_TAG
    ports:
      - "10003:8080"
    environment:
      JVM_OPTS: $JVM_OPTS
      SERVER_SSL_ENABLED: 'false'
      URL_SERVICE_DEMO: $URL_SERVICE_DEMO
      URL_SERVICE_ERROR_HANDLING: $URL_SERVICE_ERROR_HANDLING

  petstore-stub:
    image: com.kainos/petstore-stub:0.0.1-SNAPSHOT
    ports:
      - "20001:8080"
    environment:
      JVM_OPTS: $JVM_OPTS

  etcd:
    image: bitnami/etcd:3.5.13
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      ETCD_NAME: node
      ETCDCTL_API: 3
      ALLOW_NONE_AUTHENTICATION: 'yes'
      ETCD_ADVERTISE_CLIENT_URLS: $URL_ETCD

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_HEAP_OPTS: $KAFKA_HEAP_OPTS

  broker:
    image: confluentinc/cp-kafka:5.5.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: $URL_ZOOKEEPER
      KAFKA_ADVERTISED_LISTENERS: SSL://broker:9093,PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: $KAFKA_HEAP_OPTS
      KAFKA_SSL_KEYSTORE_FILENAME: broker.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: keycredential
      KAFKA_SSL_TRUSTSTORE_FILENAME: broker.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: keycredential
      KAFKA_SSL_KEY_CREDENTIALS: keycredential
      KAFKA_MESSAGE_MAX_BYTES: 52428800
    volumes:
      - ./../tls/kafka/broker.keystore.jks:/etc/kafka/secrets/broker.keystore.jks
      - ./../tls/kafka/broker.truststore.jks:/etc/kafka/secrets/broker.truststore.jks
      - ./../tls/kafka/keycredential:/etc/kafka/secrets/keycredential

  schema-registry:
    image: confluentinc/cp-schema-registry:5.5.1
    depends_on:
      - zookeeper
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: '$URL_ZOOKEEPER'
      SCHEMA_REGISTRY_CUB_KAFKA_TIMEOUT: 80