version: '3'

services:
  error-handling:
    image: com.kainos/error-handling:$DOCKER_TAG
    ports:
      - "10001:8080"
    environment:
      JVM_OPTS: $JVM_OPTS

  demo:
    image: com.kainos/demo:$DOCKER_TAG
    ports:
      - "10002:8080"
    environment:
      JVM_OPTS: $JVM_OPTS
      PETSTORE_URL: $URL_EXTERNAL_PETSTORE

  api-gateway:
    image: com.kainos/api-gateway:$DOCKER_TAG
    ports:
      - "10003:8080"
    environment:
      JVM_OPTS: $JVM_OPTS