##### APPLICATIONS

apps:
###################################
####### DEMO APP ###########
###################################
  demo:
    name: demo
    image:
      repository: ggruszecki/helm-accelerator
      tag: demo

    podAnnotations: {}

    service:
      type: NodePort
      port: 8080

    extraEnv: []
    # - name: MERCHANT_URL
    #   value: "https://merchant-svc:8080"

    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi

    volumes: []
      # - name: server-certs
      #   secretName: api-gateway
      #   mountPath: /opt/certs/api-gateway
      #   optional: false

    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 6
      targetCPUUtilizationPercentage: 80
      # targetMemoryUtilizationPercentage: 80

    imagePullSecrets:
    - name: regcred
    nodeSelector: {}
    tolerations: []
    affinity: {}

###################################
####### ERROR-HANDLING APP ##############
###################################
  errorhandling:
    name: error-handling
    image:
      repository: ggruszecki/helm-accelerator
      tag: error-handling

    podAnnotations: {}

    service:
      type: ClusterIP
      port: 8080

    extraEnv: []
    # - name: DUMMY_ENV
    #   value: "abc123"

    ### TODO - customized envFrom to load values for etcd and kafka on-demand
    # dependencies:
    #   - kafka
    #   - etcd

    ###

    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi

    volumes:
      - name: mtls-certs1
        secretName: mtls-certs1
        mountPath: /opt/certs/mtls1
        optional: false

    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 6
      targetCPUUtilizationPercentage: 80
      # targetMemoryUtilizationPercentage: 80

    imagePullSecrets:
    - name: regcred
    nodeSelector: {}
    tolerations: []
    affinity: {}