### COMMON SETUP

global:
  tag: "latest"
  replicaCount: 1

  livenessProbe:
    httpGet:
      path: /
      port: 80
      scheme: HTTP

  livenessProbeParams:
    failureThreshold: 3
    initialDelaySeconds: 60
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 5

  maxSkew: 3