##### APPLICATIONS

apps:
###################################
####### API-GATEWAY APP ###########
###################################
  apigateway:
    name: api-gateway
    image:
      repository: my-first-repository/api-gateway
      # tag: notaglobaltag

    podAnnotations: {}

    service:
      type: NodePort
      port: 8080

    extraEnv:
    - name: MERCHANT_URL
      value: "https://merchant-svc:8080"

    resources:
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi

    volumes:
      - name: server-certs
        secretName: api-gateway
        mountPath: /opt/certs/api-gateway
        optional: false
      - name: mtls-certs2
        secretName: mtls-certs2
        mountPath: /opt/certs/mtls2
        optional: true


    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 6
      targetCPUUtilizationPercentage: 80
      # targetMemoryUtilizationPercentage: 80

    imagePullSecrets: []
    nodeSelector: {}
    tolerations: []
    affinity: {}

###################################
####### MERCHANT APP ##############
###################################
  merchant:
    name: merchant
    image:
      repository: my-second-repository/merchant
      tag: notaglobaltag

    podAnnotations: {}

    service:
      type: ClusterIP
      port: 8080

    extraEnv: []
    # - name: DUMMY_ENV
    #   value: "abc123"

    resources:
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi

    volumes:
      - name: mtls-certs1
        secretName: mtls-certs1
        mountPath: /opt/certs/mtls1
        optional: false

    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 6
      targetCPUUtilizationPercentage: 80
      # targetMemoryUtilizationPercentage: 80

    imagePullSecrets: []
    nodeSelector: {}
    tolerations: []
    affinity: {}