##### APPLICATIONS

apps:
###################################
####### API-GATEWAY APP ###########
###################################
  apigateway:
    name: api-gateway
    image:
      repository: ggruszecki/helm-accelerator
      # tag: api-gateway

    podAnnotations: {}

    service:
      type: NodePort
      port: 8080

    extraEnv:
    - name: MERCHANT_URL
      value: "https://merchant-svc:8080"

    resources:
      limits:
        cpu: 1
        memory: 1536Mi
      requests:
        cpu: 500m
        memory: 1024Mi

    volumes:
      - name: server-certs
        secretName: api-gateway
        mountPath: /opt/certs/api-gateway
        optional: false
      - name: mtls-certs2
        secretName: mtls-certs2
        mountPath: /opt/certs/mtls2
        optional: true

    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 6
      targetCPUUtilizationPercentage: 80
      # targetMemoryUtilizationPercentage: 80

    imagePullSecrets:
      - name: regcred
    nodeSelector: {}
    tolerations: []
    affinity: {}