##### APPLICATIONS

apps:
###################################
####### API-GATEWAY APP ###########
###################################
  apigateway:
    name: api-gateway
    image:
      repository: ghcr.io/grzegorzgr/api-gateway
      # tag: api-gateway

    podAnnotations: {}

    service:
      type: NodePort
      port: 8080

    extraEnv:
    - name: URL_SERVICE_DEMO
      value: "http://demo-svc:8080"
    - name: URL_SERVICE_ERROR_HANDLING
      value: "http://error-handling-svc:8080"
    - name: URL_EXTERNAL_PETSTORE
      value: "http://petstore-stub-svc:8080"
    - name: SERVER_SSL_ENABLED
      value: "true"
    - name: SERVER_SSL_CLIENTAUTH
      value: "want" ### want - validate client but do not drop connection; need - full mtls

    resources:
      limits:
        cpu: 1
        memory: 1024Mi
      requests:
        cpu: 500m
        memory: 512Mi

    volumes:
      - name: server-certs
        secretName: api-gateway
        mountPath: /opt/certs/api-gateway
        optional: true
      - name: mtls-certs2
        secretName: mtls-certs2
        mountPath: /opt/certs/mtls2
        optional: true

    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 6
      targetCPUUtilizationPercentage: 80
      # targetMemoryUtilizationPercentage: 80

    imagePullSecrets:
      - name: regcred
    nodeSelector: {}
    tolerations: []
    affinity: {}