##### APPLICATIONS

apps:
###################################
####### SCHEMA-REGISTRY ##############
###################################
  schemaregistry:
    name: schema-registry
    image:
      repository: confluentinc/cp-schema-registry
      tag: 5.5.1

    podAnnotations: {}

    service:
      type: ClusterIP
      port: 8081

    extraEnv:
    - name: SCHEMA_REGISTRY_HOST_NAME
      value: "schema-registry"
    - name: SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR
      value: "1"
    - name: SCHEMA_REGISTRY_KAFKASTORE_TOPIC
      value: "_schemas"
    - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
      value: "PLAINTEXT://kafka-headless:9092"

    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi

    volumes: []

    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 6
      targetCPUUtilizationPercentage: 80
      # targetMemoryUtilizationPercentage: 80

    imagePullSecrets:
    - name: regcred
    nodeSelector: {}
    tolerations: []
    affinity: {}