### COMMON SETUP

global:
  tag: "latest"
  replicaCount: 1

  livenessProbe:
    httpGet:
      path: /
      port: 80
      scheme: HTTP

  livenessProbeParams:
    failureThreshold: 3
    initialDelaySeconds: 60
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 5

  maxSkew: 3

##### APPLICATIONS

apps:
###################################
####### API-GATEWAY APP ###########
###################################
  apigateway:
    name: api-gateway
    image:
      repository: api-gateway
      pullPolicy: IfNotPresent

    podAnnotations: {}

    service:
      type: NodePort
      port: 8080

    extraEnv:
    - name: MERCHANT_URL
      value: "https://merchant-svc:8080"

    resources:
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi

    volumes:
      - name: server-certs
        secretName: api-gateway
        mountPath: /opt/certs/api-gateway
        optional: false
      - name: mtls-certs2
        secretName: mtls-certs2
        mountPath: /opt/certs/mtls2
        optional: true


    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 6
      targetCPUUtilizationPercentage: 80
      # targetMemoryUtilizationPercentage: 80

    imagePullSecrets: []
    nodeSelector: {}
    tolerations: []
    affinity: {}

###################################
####### MERCHANT APP ##############
###################################
  merchant:
    name: merchant
    image:
      repository: merchant
      pullPolicy: IfNotPresent

    podAnnotations: {}

    service:
      type: ClusterIP
      port: 8080

    extraEnv: []
    # - name: DUMMY_ENV
    #   value: "abc123"

    resources:
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi

    volumes:
      - name: mtls-certs1
        secretName: mtls-certs1
        mountPath: /opt/certs/mtls1
        optional: false

    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 6
      targetCPUUtilizationPercentage: 80
      # targetMemoryUtilizationPercentage: 80

    imagePullSecrets: []
    nodeSelector: {}
    tolerations: []
    affinity: {}