name: Deploy
on:
  push:
    branches:
      - cleanup

jobs:
  cleanup:
    name: Cleanup
    runs-on: arc-runner-set
    container:
      image: smartpayimages/jdk-17-slim:technical

    steps:
    - name: Setup Kubernetes
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure Kubernetes
      run: |
        mkdir $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config

    - name: Setup Helm
      uses: azure/setup-helm@v1
      with:
        version: '3.14.0'

    - name: Remove apps
      run: |
        SHORT_SHA=acc-$(echo ${{ github.sha }} | cut -c1-7)
        for a in `kubectl get ns --no-headers | grep acc`; do kubectl delete ns $a; done
