name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: [arc-runner-set]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Create Namespace
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: create namespace accelerator-app --insecure-skip-tls-verify


